# Generated by Django 4.2.5 on 2023-09-12 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_chatmessageattachment_chat_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='api.project'),
        ),
    ]
